import { popGrid } from './pop_grid';
import { dialogueBox } from "./dialogue_box";
import { samplingDist } from "./samplingdist";
import {sim_x} from "./popsim";
import * as d3 from 'd3';

document.addEventListener('DOMContentLoaded', function () {
   var popgrid,
       dialoguebox,
       samplingdist,
       events;


   function build() {
      popgrid = popGrid()
          .num_cells_x(20)
          .num_cells_y(20)
          .cell_width(30);

      dialoguebox = dialogueBox();
      samplingdist = samplingDist();
   }
   
   function addToDom() {
      var pop = sim_x(popgrid.num_cells_x(), popgrid.num_cells_y(), 100, 80);

      d3.select('#grid1')
          .datum(pop)
          .call(popgrid);
      d3.select('#dialogueBox1')
      //FIXME probably a more straightforward way for this, consider accessing popgrid dimensions
          .style('width', popgrid.num_cells_x() * popgrid.cell_width()+'px')
          .style('height', 175+'px')
          .call(dialoguebox);

      // TODO static for now, but this will be generated by an event at some point
      d3.select('#samplingDist1')
          .datum(pop)
          .call(samplingdist)
   }

   function addListeners() {
      d3.select('#sampleButton1').on('click', events.start_sample);
   }

   events = {
      start_sample: function() {
         popgrid.add_up_total();
         samplingdist.add_up_total();
      }
   };

   build();
   addToDom();
   addListeners();
});